Repository josh-development/utilities, pull requests merged in 2022-10, with the labels that each got.

#96 feat: code review
  .github/CODEOWNERS
  .github/CONTRIBUTING.md
  .github/workflows/auto-deprecate.yml
  .github/workflows/continuous-delivery.yml
  .vscode/settings.json
  packages/provider/jest.config.mjs
  packages/provider/src/lib/decorators/ApplyMiddlewareOptions.ts
  packages/provider/src/lib/decorators/PostProvider.ts
  packages/provider/src/lib/decorators/PreProvider.ts
  packages/provider/src/lib/decorators/utils/createProxy.ts
  packages/provider/src/lib/functions/resolveCommonIdentifier.ts
  packages/provider/src/lib/functions/resolveVersion.ts
  packages/provider/src/lib/functions/validators/Every.ts
  packages/provider/src/lib/functions/validators/Filter.ts
  packages/provider/src/lib/functions/validators/Find.ts
  packages/provider/src/lib/functions/validators/Map.ts
  packages/provider/src/lib/functions/validators/Partition.ts
  packages/provider/src/lib/functions/validators/Remove.ts
  packages/provider/src/lib/functions/validators/Some.ts
  packages/provider/src/lib/functions/validators/WithData.ts
  packages/provider/src/lib/structures/JoshMiddleware.ts
  packages/provider/src/lib/structures/JoshMiddlewareStore.ts
  packages/provider/src/lib/structures/JoshProvider.ts
  packages/provider/src/lib/structures/JoshProviderError.ts
  packages/provider/src/lib/types/CommonIdentifiers.ts
  packages/provider/src/lib/types/MathOperator.ts
  packages/provider/src/lib/types/Method.ts
  packages/provider/src/lib/types/Payload.ts
  packages/provider/src/lib/types/Payloads.ts
  packages/provider/src/lib/types/Semver.ts
  packages/provider/src/lib/types/Trigger.ts
  packages/provider/src/lib/types/index.ts
  packages/provider/src/tests/runProviderTest.ts
  packages/provider/tests/lib/structures/JoshProvider.test.ts
  packages/provider/vitest.config.ts
  packages/serialize/README.md
  packages/serialize/jest.config.mjs
  packages/serialize/src/lib/Serialize.ts
  packages/serialize/tests/lib/Serialize.test.ts
  packages/serialize/vitest.config.ts
  scripts/vitest.config.ts
Labels: feature, help wanted, in progress

#113 feat(provider): export `resolveVersion`
  packages/provider/src/lib/functions/index.ts
Labels: feature, priority:critical, packages:provider

#114 feat: add `@joshdb/eslint-config`
  .eslintrc
  .github/labels.yml
  .npm-deprecaterc.yml
  README.md
  package.json
  packages/eslint-config/.cliff-jumperrc.yml
  packages/eslint-config/CHANGELOG.md
  packages/eslint-config/README.md
  packages/eslint-config/cliff.toml
  packages/eslint-config/eslint-config.json
  packages/eslint-config/package.json
  packages/eslint-config/tsconfig.eslint.json
  yarn.lock
Labels: feature

#115 feat: add `@joshdb/prettier-config`
  .github/labels.yml
  .npm-deprecaterc.yml
  .prettierrc.js
  README.md
  packages/prettier-config/.cliff-jumperrc.yml
  packages/prettier-config/.prettierrc.json
  packages/prettier-config/CHANGELOG.md
  packages/prettier-config/README.md
  packages/prettier-config/cliff.toml
  packages/prettier-config/package.json
  packages/prettier-config/tsconfig.eslint.json
  yarn.lock
Labels: feature

#116 feat: add `@joshdb/ts-config`
  README.md
  packages/ts-config/.cliff-jumperrc.yml
  packages/ts-config/CHANGELOG.md
  packages/ts-config/README.md
  packages/ts-config/cliff.toml
  packages/ts-config/package.json
  packages/ts-config/tsconfig.eslint.json
  packages/ts-config/tsconfig.json
  tsconfig.base.json
  yarn.lock
Labels: feature
