Repository josh-development/utilities, pull requests merged in 2022-09, with the labels that each got.

#85 refactor(serialize)!: switch to a `Serialize` namespace
  packages/serialize/src/index.ts
  packages/serialize/src/lib/Serialize.ts
  packages/serialize/src/lib/toJSON.ts
  packages/serialize/src/lib/toRaw.ts
  packages/serialize/src/lib/types/SerializeJSON.ts
  packages/serialize/src/lib/types/SerializeType.ts
  packages/serialize/src/lib/types/index.ts
  packages/serialize/tests/lib/Serialize.test.ts
  packages/serialize/tests/lib/toJSON.test.ts
  packages/serialize/tests/lib/toRaw.test.ts
Labels: priority:high, refactor, semver:major

#84 fix(runProviderTest): return `[]` when empty provider in `Method.Random/RandomKey`
  packages/provider/src/tests/runProviderTest.ts
Labels: priority:critical, semver:patch

#86 test(*): increase coverage
  jest.config.mjs
  packages/provider/package.json
  packages/provider/src/lib/functions/resolveCommonIdentifier.ts
  packages/provider/tests/lib/functions/resolveCommonIdentifier.test.ts
  packages/provider/tests/lib/functions/validators/Every.test.ts
  packages/provider/tests/lib/functions/validators/Filter.test.ts
  packages/provider/tests/lib/functions/validators/Find.test.ts
  packages/provider/tests/lib/functions/validators/Map.test.ts
  packages/provider/tests/lib/functions/validators/Partition.test.ts
  packages/provider/tests/lib/functions/validators/Remove.test.ts
  packages/provider/tests/lib/functions/validators/Some.test.ts
  packages/provider/tests/lib/functions/validators/WithData.test.ts
  packages/serialize/package.json
  yarn.lock
Labels: tests

#87 fix(runProviderTest): add coverage for `Method.SetMany` overwrite
  packages/provider/src/tests/runProviderTest.ts
Labels: semver:patch, tests

#91 chore(scripts): remove `generate` script
  package.json
  scripts/generate/generate.mjs
  scripts/generate/jobs.mjs
Labels: chore
