Repository josh-development/utilities, pull requests merged in 2023-09, with the labels that each got.

#257 chore(deps): update dependency typedoc-json-parser to ^9.0.0
  packages/eslint-config/package.json
  packages/prettier-config/package.json
  packages/provider/package.json
  packages/serialize/package.json
  packages/ts-config/package.json
  yarn.lock
Labels: dependencies

#244 chore(deps): update dev-dependencies
  .husky/pre-commit
  package.json
  packages/eslint-config/eslint-config.json
  packages/eslint-config/package.json
  packages/prettier-config/README.md
  packages/prettier-config/package.json
  packages/provider/package.json
  packages/provider/rollup.config.ts
  packages/provider/src/lib/decorators/PostProvider.ts
  packages/provider/src/lib/decorators/PreProvider.ts
  packages/provider/src/lib/functions/resolveCommonIdentifier.ts
  packages/provider/src/lib/structures/JoshMiddleware.ts
  packages/provider/src/lib/structures/JoshProvider.ts
  packages/provider/src/tests/runProviderTest.ts
  packages/provider/src/tsconfig.json
  packages/provider/tests.d.ts
  packages/provider/tests.js
  packages/provider/tests.mjs
  packages/provider/tsconfig.eslint.json
  packages/provider/tsup.config.ts
  packages/serialize/package.json
  packages/serialize/rollup.config.ts
  packages/serialize/src/lib/Serialize.ts
  packages/serialize/src/tsconfig.json
  packages/serialize/tsconfig.eslint.json
  packages/serialize/tsup.config.ts
  packages/ts-config/README.md
  packages/ts-config/package.json
  packages/ts-config/src/bundler.json
  packages/ts-config/src/decorators.json
  packages/ts-config/src/extra-strict.json
  packages/ts-config/src/tsconfig.json
  packages/ts-config/src/verbatim.json
  scripts/tsup.config.ts
  tsconfig.base.json
  yarn.lock
Labels: blocked, dependencies

#227 fix(runProviderTest): add tests for `Method.Math`
  packages/provider/src/lib/functions/doMath.ts
  packages/provider/src/lib/functions/index.ts
  packages/provider/src/lib/structures/JoshProvider.ts
  packages/provider/src/tests/runProviderTest.ts
  packages/provider/tests/lib/functions/doMath.test.ts
Labels: tests
